#!/usr/bin/env bash

USERNAME=antonpegov
VERSION=0.0.1

# Users microservice
IMAGE=auditdb-users

docker build -f ./apps/users/Dockerfile --target production -t $USERNAME/$IMAGE:latest . && \
docker tag $USERNAME/$IMAGE:latest $USERNAME/$IMAGE:$VERSION && \
docker push $USERNAME/$IMAGE:latest && \
docker push $USERNAME/$IMAGE:$VERSION

# Auditors microservice
IMAGE=auditdb-auditors

docker build -f ./apps/auditors/Dockerfile --target production -t $USERNAME/$IMAGE:latest . && \
docker tag $USERNAME/$IMAGE:latest $USERNAME/$IMAGE:$VERSION && \
docker push $USERNAME/$IMAGE:latest && \
docker push $USERNAME/$IMAGE:$VERSION

# Projects microservice
IMAGE=auditdb-projects

docker build -f ./apps/projects/Dockerfile --target production -t $USERNAME/$IMAGE:latest . && \
docker tag $USERNAME/$IMAGE:latest $USERNAME/$IMAGE:$VERSION && \
docker push $USERNAME/$IMAGE:latest && \
docker push $USERNAME/$IMAGE:$VERSION

# Swagger web
IMAGE=auditdb-swagger

docker build -f ./swagger/Dockerfile -t $USERNAME/$IMAGE:latest . && \
docker tag $USERNAME/$IMAGE:latest $USERNAME/$IMAGE:$VERSION && \
docker push $USERNAME/$IMAGE:latest && \
docker push $USERNAME/$IMAGE:$VERSION


